# Pages definitions; final sequence of pages is defined at the bottom of the page

EXTERNAL_SOURCES_OPEN_QUESTION_1 = {
    "type": "form",
    "form_id": "external_sources_open_question_1",
    "form_title": "Open question",
    "allow_revisit": False,
    "questions": [
        {
            "question_id": "q1",
            "prompt": "Were the explanations in the chat sufficient to answer the questions in the previous questionnaire?\n\nThis question is not relevant to your bonus.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": ["yes", "no"],
        },
        {
            "question_id": "q2",
            "prompt": "If not, why?",
            "type": "text",
            "required": False,
            "attention_check_question": False,
        },
    ],
}

EXTERNAL_SOURCES_OPEN_QUESTION_2 = {
    "type": "form",
    "form_id": "external_sources_open_question_2",
    "form_title": "Open question",
    "allow_revisit": False,
    "questions": [
        {
            "question_id": "q1",
            "prompt": "Were the explanations in the chat sufficient to answer the questions in the previous questionnaire?\n\nThis question is not relevant to your bonus.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": ["yes", "no"],
        },
        {
            "question_id": "q2",
            "prompt": "If not, why?",
            "type": "text",
            "required": False,
            "attention_check_question": False,
        },
    ],
}

SLEEPCYCLE_QUESTIONNAIRE_TO_CHAT_TRANSITION_PAGE = {
    "type": "transition",
    "allow_revisit": True,
    "text": "Start chatting!",
    "subtext": "Your task is now to chat and learn as much as possible about the human sleep cycle and its stages. Chat until either your time is up or you believe you can explain the topic in detail to someone.\nPlease chat in English. You can chat for a maximum of 15 minutes.\n\nAfter the chat, you will be asked to complete four questionnaires. Two of the questionnaires will test your knowledge of sleeps cycles and its stages. You will receive a bonus of £1.50 if you participate in the chat by asking questions about the topic and showing active motivation to learn throughout the chat.",
}

BLACKHOLES_QUESTIONNAIRE_TO_CHAT_TRANSITION_PAGE = {
    "type": "transition",
    "allow_revisit": True,
    "text": "Start chatting!",
    "subtext": "Your task is now to chat and learn as much as possible about the formation of black holes. Chat until either your time is up or you believe you can explain the topic in detail to someone.\nPlease chat in English. You can chat for a maximum of 15 minutes.\n\nAfter the chat, you will be asked to complete four questionnaires. Two of the questionnaires will test your knowledge of the formation of black holes. You will receive a bonus of £1.50 if you participate in the chat by asking questions about the topic and showing active motivation to learn throughout the chat.",
}

QUARTO_QUESTIONNAIRE_TO_CHAT_TRANSITION_PAGE = {
    "type": "transition",
    "allow_revisit": True,
    "text": "Start chatting!",
    "subtext": "Your task is now to chat and learn as much as possible about the strategic board game Quarto and its rules. Chat until either your time is up or you believe you can explain the game in detail to someone.\nPlease chat in English. You can chat for a maximum of 15 minutes.\n\nAfter the chat, you will be asked to complete four questionnaires. Two of the questionnaires will test your knowledge of the game. You will receive a bonus of £1.50 if you participate in the chat by asking questions about the game and showing active motivation to learn throughout the chat.",
}

CHAT_PAGE = {
    "type": "chat",
    "form_id": "chat",
    "allow_revisit": True,
}

CHAT_TO_QUESTIONNAIRE_TRANSITION_PAGE = {
    "type": "transition",
    "allow_revisit": False,
    "text": "Are you done with chatting?",
    "subtext": "If you continue, you won't be able to return to the chat. Instead, you'll start the next questionnaire.",
}

COCONSTRUCT_POST_QUESTIONNAIRE_PAGE = {
    "type": "form",
    "form_id": "coconstruct_post",
    "allow_revisit": False,
    "form_title": "Questionaire 5",
    "subtext": "You will be presented with different statements about your dialogue partner, that you are asked to assess. Answer every statement spontaneously and with an open mind. Try not to get confused if some of the statements are very similar to each other.",
    "questions": [
        {
            "question_id": "q1",
            "prompt": "My dialogue partner carefully adapted their utterances to my utterances.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q2",
            "prompt": "My dialogue partner considered my understanding.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q3",
            "prompt": "While explaining, my dialogue partner met me halfway.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q4",
            "prompt": "My dialogue partner took my statements into account.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q5",
            "prompt": "The explanation was meant to encourage me to question my understanding.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q6",
            "prompt": "My dialogue partner intended to provide me with the opportunity to build an understanding of the topic by asking questions.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q7",
            "prompt": "My dialogue partner encouraged me to continuously think about further details of the topic.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q8",
            "prompt": "When learning about a new topic, it’s better to think about details yourself, rather than having everything fully explained.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q9",
            "prompt": "My dialogue partner encouraged me to visualize the different processes of the topic.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q10",
            "prompt": "While explaining, it was important to my dialogue partner to continuously consider if I understood the explanation.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q11",
            "prompt": "While explaining, it was important to my dialogue partner to monitor whether I understood everything.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q12",
            "prompt": "My dialogue partner responded when I signaled non-understanding.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q13",
            "prompt": "Please specify additional behavior of your dialogue partner during the chat that helped you better understand the explanations. This is an open answer. Be as specific or unspecific as you like.",
            "type": "text",
            "required": False,
            "attention_check_question": False,
        },
    ],
}

SLEEPCYCLE_SUBJECTIVE_UNDERSTANDING_PRE_QUESTIONNAIRE_PAGE = {
    "type": "form",
    "form_id": "subjective_understanding_pre",
    "allow_revisit": False,
    "form_title": "Questionnaire 1",
    "subtext": "Your topic is the human sleep cycle and its stages. You will be presented with different statements that you are asked to assess. Answer every statement spontaneously and with an open mind. Try not to get confused if some of the statements are very similar to each other.",
    "questions": [
        {
            "question_id": "q1",
            "prompt": "I have prior knowledge of sleep cycles.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q2",
            "prompt": "I’m a real expert on the topic of sleep cycles.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q3",
            "prompt": "At some point in the past, I did study sleep cycles.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q4",
            "prompt": "I know a lot about sleep cycles.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q5",
            "prompt": "I understand what the sleep stages of a sleep cycle are.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q6",
            "prompt": "I can explain the sleep stages of a sleep cycle.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q7",
            "prompt": "I know the sleep stages of a sleep cycle.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q8",
            "prompt": "I’m motivated to learn something new about sleep cycles.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "attention-q1",
            "prompt": "I think that sleep cycles are not real. Please answer this question with 'disagree'.",
            "type": "radio",
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
            "required": True,
            "attention_check_question": True,
            "correct_answers": ["disagree"],
        },
        {
            "question_id": "q9",
            "prompt": "I find the topic of sleep cycles very exciting.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q10",
            "prompt": "I would also engage in the topic of sleep cycles in my free time.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q11",
            "prompt": "In general, I find the topic of sleep cycles boring.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q12",
            "prompt": "I have fun engaging in the topic of sleep cycles.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "attention-q2",
            "prompt": "I think that sleep cycles are a phenomenon studied by many different fields of research. Please answer this question with 'agree'.",
            "type": "radio",
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
            "required": True,
            "attention_check_question": True,
            "correct_answers": ["agree"],
        },
        {
            "question_id": "q13",
            "prompt": "I want to deepen my understanding of sleep cycles to know more about it.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q14",
            "prompt": "I want to deepen my understanding of sleep cycles to know more about it than others.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q15",
            "prompt": "I want to deepen my understanding of sleep cycles to be the best in the field.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q16",
            "prompt": "I want to be acknowledged by others through my knowledge about sleep cycles.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
    ],
}

BLACKHOLES_SUBJECTIVE_UNDERSTANDING_PRE_QUESTIONNAIRE_PAGE = {
    "type": "form",
    "form_id": "subjective_understanding_pre",
    "allow_revisit": False,
    "form_title": "Questionnaire 1",
    "subtext": "Your topic is the formation of black holes. You will be presented with different statements that you are asked to assess. Answer every statement spontaneously and with an open mind. Try not to get confused if some of the statements are very similar to each other.",
    "questions": [
        {
            "question_id": "q1",
            "prompt": "I have prior knowledge of black holes.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q2",
            "prompt": "I’m a real expert on the topic of black holes.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q3",
            "prompt": "At some point in the past, I did study the topic of black holes.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q4",
            "prompt": "I know a lot about black holes.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q5",
            "prompt": "I understand what black holes are and the mechanics of their formation.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q6",
            "prompt": "I can explain how black holes form and what leads to their formation.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q7",
            "prompt": "I know the process of black holes forming.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q8",
            "prompt": "I’m motivated to learn something new about black holes.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "attention-q1",
            "prompt": "I think that black holes cannot just form but simply have always existed. Please answer this question with 'disagree'.",
            "type": "radio",
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
            "required": True,
            "attention_check_question": True,
            "correct_answers": ["disagree"],
        },
        {
            "question_id": "q9",
            "prompt": "I find the topic of black holes exciting.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q10",
            "prompt": "I would also engage in the topic of black holes in my free time.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q11",
            "prompt": "In general, I find the topic of black holes boring.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q12",
            "prompt": "I have fun engaging in the topic of black holes.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "attention-q2",
            "prompt": "I think that black holes are a phenomenon studied in the field of physics. Please answer this question with 'agree'.",
            "type": "radio",
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
            "required": True,
            "attention_check_question": True,
            "correct_answers": ["agree"],
        },
        {
            "question_id": "q13",
            "prompt": "I want to deepen my understanding of black holes to know more about it.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q14",
            "prompt": "I want to deepen my understanding of black holes to know more about it than others.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q15",
            "prompt": "I want to deepen my understanding of black holes to be the best in the field.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q16",
            "prompt": "I want to be acknowledged by others through my knowledge about black holes.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
    ],
}

QUARTO_SUBJECTIVE_UNDERSTANDING_PRE_QUESTIONNAIRE_PAGE = {
    "type": "form",
    "form_id": "subjective_understanding_pre",
    "allow_revisit": False,
    "form_title": "Questionnaire 1",
    "subtext": "Your topic is the strategic board game Quarto and its rules. You will be presented different statements that you are asked to assess. Answer every statement spontaneously and with an open mind. Try not to get confused if some of the statements are very similar to each other.",
    "questions": [
        {
            "question_id": "q1",
            "prompt": "I have prior knowledge of games.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q2",
            "prompt": "I’m a real game expert.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q3",
            "prompt": "I have experience with strategy games.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q4",
            "prompt": "I know a lot about games.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q5",
            "prompt": "I can follow the rules of Quarto.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q6",
            "prompt": "I can apply the rules of Quarto.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q7",
            "prompt": "I know the rules of Quarto.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q8",
            "prompt": "I’m motivated to learn something new about Quarto.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "attention-q1",
            "prompt": "I know that Quarto is not a strategic board game. Please answer this question with 'disagree'.",
            "type": "radio",
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
            "required": True,
            "attention_check_question": True,
            "correct_answers": ["disagree"],
        },
        {
            "question_id": "q9",
            "prompt": "I find games like this exciting.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q10",
            "prompt": "I would also play such a game in my free time.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q11",
            "prompt": "In general, I find games boring.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q12",
            "prompt": "I have fun playing games.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "attention-q2",
            "prompt": "I think that board games can have a stategic component. Please answer this question with 'agree'.",
            "type": "radio",
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
            "required": True,
            "attention_check_question": True,
            "correct_answers": ["agree"],
        },
        {
            "question_id": "q13",
            "prompt": "I want to deepen my understanding of games to know more about it.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q14",
            "prompt": "I want to deepen my understanding of games to know more about it than others.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q15",
            "prompt": "I want to deepen my understanding of games to be the best in the field.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q16",
            "prompt": "I want to be acknowledged by others through my knowledge about games.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
    ],
}

SLEEPCYCLE_SUBJECTIVE_UNDERSTANDING_POST_QUESTIONNAIRE_PAGE = {
    "type": "form",
    "form_id": "subjective_understanding_post",
    "allow_revisit": False,
    "form_title": "Questionaire 2",
    "subtext": "You will now be presented with the statements of the first questionnaire again. Please assess these questions for your current situation, after having finished the chat. Answer every statement spontaneously and with an open mind. Try not to get confused if some of the statements are very similar to each other.",
    "questions": [
        {
            "question_id": "q1",
            "prompt": "I’m a real expert on the topic of sleep cycles.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q2",
            "prompt": "I know a lot about sleep cycles.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q3",
            "prompt": "I understand what the sleep stages of a sleep cycle are.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q4",
            "prompt": "I can explain the sleep stages of a sleep cycle.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q5",
            "prompt": "I know the sleep stages of a sleep cycle.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q6",
            "prompt": "I was motivated by the explanation to discover new connections between the concepts related to sleep cycles and its stages.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q7",
            "prompt": "I found the explanation to be very interesting.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q8",
            "prompt": "I had fun understanding the explanations.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q9",
            "prompt": "I find the topic of sleep cycles very exciting.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q10",
            "prompt": "I would also engage in the topic of sleep cycles in my free time.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q11",
            "prompt": "In general, I find the topic of sleep cycles boring.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q12",
            "prompt": "I have fun engaging in the topic of sleep cycles.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q13",
            "prompt": "I want to deepen my understanding of sleep cycles to know more about it.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q14",
            "prompt": "I want to deepen my understanding of sleep cycles to know more about it than others.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q15",
            "prompt": "I want to deepen my understanding of sleep cycles to be the best in the field.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q16",
            "prompt": "I want to be acknowledged by others through my knowledge about sleep cycles.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
    ],
}

BLACKHOLES_SUBJECTIVE_UNDERSTANDING_POST_QUESTIONNAIRE_PAGE = {
    "type": "form",
    "form_id": "subjective_understanding_post",
    "allow_revisit": False,
    "form_title": "Questionaire 2",
    "subtext": "You will now be presented with the statements of the first questionnaire again. Please assess these questions for your current situation, after having finished the chat. Answer every statement spontaneously and with an open mind. Try not to get confused if some of the statements are very similar to each other.",
    "questions": [
        {
            "question_id": "q1",
            "prompt": "I’m a real expert on the topic of black holes.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q2",
            "prompt": "I know a lot about black holes.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q3",
            "prompt": "I understand what black holes are and the mechanics of their formation.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q4",
            "prompt": "I can explain how black holes form and what leads to their formation.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q5",
            "prompt": "I know the process of black holes forming.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q6",
            "prompt": "I was motivated by the explanation to discover new connections between the concepts related to the formation of black holes.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q7",
            "prompt": "I found the explanation to be very interesting.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q8",
            "prompt": "I had fun understanding the explanations.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q9",
            "prompt": "I find the topic of black holes exciting.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q10",
            "prompt": "I would also engage in the topic of black holes in my free time.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q11",
            "prompt": "In general, I find the topic of black holes boring.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q12",
            "prompt": "I have fun engaging in the topic of black holes.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q13",
            "prompt": "I want to deepen my understanding of black holes to know more about it.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q14",
            "prompt": "I want to deepen my understanding of black holes to know more about it than others.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q15",
            "prompt": "I want to deepen my understanding of black holes to be the best in the field.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q16",
            "prompt": "I want to be acknowledged by others through my knowledge about black holes.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
    ],
}

QUARTO_SUBJECTIVE_UNDERSTANDING_POST_QUESTIONNAIRE_PAGE = {
    "type": "form",
    "form_id": "subjective_understanding_post",
    "allow_revisit": False,
    "form_title": "Questionaire 2",
    "subtext": "You will now be presented with the statements of the first questionnaire again. Please assess these questions for your current situation, after having finished the chat. Answer every statement spontaneously and with an open mind. Try not to get confused if some of the statements are very similar to each other.",
    "questions": [
        {
            "question_id": "q1",
            "prompt": "I’m a real game expert.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q2",
            "prompt": "I know a lot about games.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q3",
            "prompt": "I can follow the rules of Quarto.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q4",
            "prompt": "I can apply the rules of Quarto.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q5",
            "prompt": "I know the rules of Quarto.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q6",
            "prompt": "I was motivated by the explanation to discover new connections between the concepts related to Quarto and its rules.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q7",
            "prompt": "I found the explanation to be very interesting.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q8",
            "prompt": "I had fun understanding the explanations.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q9",
            "prompt": "I find games like this exciting.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q10",
            "prompt": "I would also play such a game in my free time.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q11",
            "prompt": "In general, I find games boring.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q12",
            "prompt": "I have fun playing games.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q13",
            "prompt": "I want to deepen my understanding of games to know more about it.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q14",
            "prompt": "I want to deepen my understanding of games to know more about it than others.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q15",
            "prompt": "I want to deepen my understanding of games to be the best in the field.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
        {
            "question_id": "q16",
            "prompt": "I want to be acknowledged by others through my knowledge about games.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "strongly agree",
                "agree",
                "neutral",
                "disagree",
                "strongly disagree",
            ],
        },
    ],
}

SLEEPCYCLE_OBJECTIVE_UNDERSTANDING_POST_QUESTIONNAIRE_PAGE = {
    "type": "form",
    "form_id": "objective_understanding_post",
    "form_title": "Questionnaire 3",
    "allow_revisit": True,
    "subtext": "The following section of the questionnaire will be about your description and assessment of the sleep cycle and its sleep stages. You will be presented with different statements that you are asked to assess.",
    "questions": [
        {
            "question_id": "q1",
            "prompt": "The sleep cycle always runs in fixed stages.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": ["yes", "no"],
            "correct_answers": ["no"],
        },
        {
            "question_id": "q2",
            "prompt": "Sleep cycles can be altered by external influences such as light and temperature.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": ["yes", "no"],
            "correct_answers": ["yes"],
        },
        {
            "question_id": "q3",
            "prompt": "Slow-wave sleep is crucial for physical recovery.",
            "type": "radio",
            "options": ["yes", "no"],
            "correct_answers": ["yes"],
        },
        {
            "question_id": "q4",
            "prompt": "Everyone needs the same amount of sleep.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": ["yes", "no"],
            "correct_answers": ["no"],
        },
        {
            "question_id": "q5",
            "prompt": "A complete sleep cycle lasts about 60 minutes.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": ["yes", "no"],
            "correct_answers": ["no"],
        },
        {
            "question_id": "q6",
            "prompt": "There are five sleep stages.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": ["yes", "no"],
            "correct_answers": ["no"],
        },
        {
            "question_id": "q7",
            "prompt": "Melatonin production is highest during REM sleep.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": ["yes", "no"],
            "correct_answers": ["no"],
        },
        {
            "question_id": "q8",
            "prompt": "We only dream during REM sleep.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": ["yes", "no"],
            "correct_answers": ["no"],
        },
        {
            "question_id": "q9",
            "prompt": "Our body temperature and heart rate drop during slow-wave sleep.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": ["yes", "no"],
            "correct_answers": ["yes"],
        },
        {
            "question_id": "q10",
            "prompt": "It’s harmful to wake up during REM sleep.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": ["yes", "no"],
            "correct_answers": ["no"],
        },
        {
            "question_id": "q11",
            "prompt": "Slow-wave sleep is dominated by delta waves with frequencies below 4 Hz.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": ["yes", "no"],
            "correct_answers": ["yes"],
        },
        {
            "question_id": "q12",
            "prompt": "Melatonin and Cortisol are primarily involved in regulating the sleep-wake cycle.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": ["yes", "no"],
            "correct_answers": ["yes"],
        },
        {
            "question_id": "q13",
            "prompt": "Serotonin is the primary neurotransmitter responsible for REM sleep.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": ["yes", "no"],
            "correct_answers": ["no"],
        },
        {
            "question_id": "q14",
            "prompt": "Alpha waves play a role in the initial sleep onset.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": ["yes", "no"],
            "correct_answers": ["yes"],
        },
    ],
}

BLACKHOLES_OBJECTIVE_UNDERSTANDING_POST_QUESTIONNAIRE_PAGE = {
    "type": "form",
    "form_id": "objective_understanding_post",
    "form_title": "Questionnaire 3",
    "allow_revisit": True,
    "subtext": "The following section of the questionnaire will be about your description and assessment of black holes and their formation. You will be presented with different statements that you are asked to assess.",
    "questions": [
        {
            "question_id": "q1",
            "prompt": "All black holes form in the same way.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": ["yes", "no"],
            "correct_answers": ["no"],
        },
        {
            "question_id": "q2",
            "prompt": "Black holes are the densest objects in the universe.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": ["yes", "no"],
            "correct_answers": ["yes"],
        },
        {
            "question_id": "q3",
            "prompt": "Black holes can form if the core of a star collapses.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": ["yes", "no"],
            "correct_answers": ["yes"],
        },
        {
            "question_id": "q4",
            "prompt": "If the core of a star collapses, it can either form a black hole or a neutron star.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": ["yes", "no"],
            "correct_answers": ["no"],
        },
        {
            "question_id": "q5",
            "prompt": "The reason for the core of a star collapsing is that it is depleted of energy (aka. fuel to burn).",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": ["yes", "no"],
            "correct_answers": ["yes"],
        },
        {
            "question_id": "q6",
            "prompt": "When the core of a star collapses, the result is always the formation of a black hole.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": ["yes", "no"],
            "correct_answers": ["no"],
        },
        {
            "question_id": "q7",
            "prompt": "Any type of star can form a black hole, if the core of the star collapses.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": ["yes", "no"],
            "correct_answers": ["no"],
        },
        {
            "question_id": "q8",
            "prompt": "The width of a star is the main factor influencing the mass of a black hole that results from the star’s death.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": ["yes", "no"],
            "correct_answers": ["no"],
        },
        {
            "question_id": "q9",
            "prompt": "The explosion of the outer shell of a star that happens due to its core collapsing is called a supernova.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": ["yes", "no"],
            "correct_answers": ["yes"],
        },
        {
            "question_id": "q10",
            "prompt": "The sun has enough mass to form a black hole.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": ["yes", "no"],
            "correct_answers": ["no"],
        },
        {
            "question_id": "q11",
            "prompt": "When a beam of light crosses the event horizon of a black hole, it comes out on the opposite side.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": ["yes", "no"],
            "correct_answers": ["no"],
        },
        {
            "question_id": "q12",
            "prompt": "The process of two black holes merging can create gravitational waves that are measurable on Earth.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": ["yes", "no"],
            "correct_answers": ["yes"],
        },
        {
            "question_id": "q13",
            "prompt": "Black holes can also form without the core of a star collapsing.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": ["yes", "no"],
            "correct_answers": ["yes"],
        },
        {
            "question_id": "q14",
            "prompt": "The mass, spin, and electric charge of a black hole is determined when it forms and does not change throughout its lifetime.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": ["yes", "no"],
            "correct_answers": ["no"],
        },
    ],
}

QUARTO_OBJECTIVE_UNDERSTANDING_POST_QUESTIONNAIRE_PAGE = {
    "type": "form",
    "form_id": "objective_understanding_post",
    "form_title": "Questionnaire 3",
    "allow_revisit": True,
    "subtext": "The following section of the questionnaire will be about your description and assessment of the game, its components, and rules. You will be presented with different statements that you are asked to assess.",
    "questions": [
        {
            "question_id": "q1",
            "prompt": "One may only complete the rows that they have started themselves.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": ["yes", "no"],
            "correct_answers": ["no"],
        },
        {
            "question_id": "q2",
            "prompt": "One may complete a row that the other person has started and thus win.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": ["yes", "no"],
            "correct_answers": ["yes"],
        },
        {
            "question_id": "q3",
            "prompt": "It is allowed to block a row that the other person has started in order to avoid losing.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": ["yes", "no"],
            "correct_answers": ["yes"],
        },
        {
            "question_id": "q4",
            "prompt": "One chooses the piece that they place themselves.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": ["yes", "no"],
            "correct_answers": ["no"],
        },
        {
            "question_id": "q5",
            "prompt": "One may position pieces anywhere on free spaces on the board.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": ["yes", "no"],
            "correct_answers": ["yes"],
        },
        {
            "question_id": "q6",
            "prompt": "One may also form a quarto diagonally.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": ["yes", "no"],
            "correct_answers": ["yes"],
        },
        {
            "question_id": "q7",
            "prompt": "All pieces have different sizes.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": ["yes", "no"],
            "correct_answers": ["no"],
        },
        {
            "question_id": "q8",
            "prompt": "All pieces have different colors.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": ["yes", "no"],
            "correct_answers": ["no"],
        },
        {
            "question_id": "q9",
            "prompt": "All pieces have different shapes.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": ["yes", "no"],
            "correct_answers": ["no"],
        },
        {
            "question_id": "q10",
            "prompt": "The game board has an even number of squares.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": ["yes", "no"],
            "correct_answers": ["yes"],
        },
        {
            "question_id": "q11",
            "prompt": "There are a total of ten possible rows to form a quarto on the field.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": ["yes", "no"],
            "correct_answers": ["yes"],
        },
        {
            "question_id": "q12",
            "prompt": "One person plays the light pieces and one person plays the dark pieces.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": ["yes", "no"],
            "correct_answers": ["no"],
        },
        {
            "question_id": "q13",
            "prompt": "One should always complete the row that the other person has started.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": ["yes", "no"],
            "correct_answers": ["no"],
        },
        {
            "question_id": "q14",
            "prompt": "One may only form a quarto with their own rows.",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": ["yes", "no"],
            "correct_answers": ["no"],
        },
    ],
}

SLEEPCYCLE_OBJECTIVE_CHOICE_UNDERSTANDING_POST_QUESTIONNAIRE_PAGE = {
    "type": "form",
    "form_id": "objective_understanding_post_choice",
    "form_title": "Questionnaire 4",
    "allow_revisit": True,
    "subtext": "The following section of the questionnaire will be about your knowledge and ability to assess situations related to sleep cycles.",
    "questions": [
        {
            "question_id": "q1",
            "prompt": "During a sleep study, a participant is observed to have a high level of alpha wave activity (8-12 Hz). What does this suggest about their current state of sleep?",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "They are likely experiencing restorative processes.",
                "They may be in a state of wakefulness or light sleep.",
                "They are in a slow-wave sleep with minimal brain activity.",
            ],
            "correct_answers": [
                "They may be in a state of wakefulness or light sleep."
            ],
        },
        {
            "question_id": "q2",
            "prompt": "A person's sleep was monitored. The result is plotted in the sleep graph seen below. What sleep stage does the yellow segment (marked with an arrow) represent?",
            "image_url": "/static/images/sleep_stages_figure.svg",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": ["Light sleep", "Slow-wave sleep", "Moderate sleep"],
            "correct_answers": ["Moderate sleep"],
        },
        {
            "question_id": "q3",
            "prompt": "A person exhibits prolonged periods of slow-wave sleep during the first half of the night, with a gradual increase in REM duration towards the morning. What does this pattern most likely indicate about their sleep architecture?",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "A typical and healthy sleep cycle progression.",
                "An unusual dominance of slow-wave sleep throughout the night.",
                "A lack of REM rebound, possibly due to prior sleep deprivation.",
            ],
            "correct_answers": ["A typical and healthy sleep cycle progression."],
        },
        {
            "question_id": "q4",
            "prompt": "If someone only gets about 5 hours of sleep per night, which sleep stages are most likely to be impacted?",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "Light and moderate sleep",
                "REM sleep and slow-wave sleep",
                "Only slow-wave sleep",
                "All sleep stages equally",
            ],
            "correct_answers": ["REM sleep and slow-wave sleep"],
        },
        {
            "question_id": "q5",
            "prompt": "Which of the following is a correct sequence of sleep stages in one complete sleep cycle?",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "Light sleep → Moderate sleep → REM → Slow-wave sleep",
                "REM → Light sleep → Moderate sleep → Slow-wave sleep",
                "Light sleep → Moderate sleep → Slow-wave sleep → REM",
                "Slow-wave sleep → Moderate sleep → Light sleep → REM",
            ],
            "correct_answers": ["Light sleep → Moderate sleep → Slow-wave sleep → REM"],
        },
    ],
}

BLACKHOLES_OBJECTIVE_CHOICE_UNDERSTANDING_POST_QUESTIONNAIRE_PAGE = {
    "type": "form",
    "form_id": "objective_understanding_post_choice",
    "form_title": "Questionnaire 4",
    "allow_revisit": True,
    "subtext": "The following section of the questionnaire will be about your knowledge and ability to assess situations related to black holes.",
    "questions": [
        {
            "question_id": "q1",
            "prompt": "Which of the following scenarios is most likely to lead to the formation of a black hole?",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "The core of a star that is the size of the sun runs out of fuel and its core collapses.",
                "A supernova that is the result of two massive stars colliding.",
                "The core of a planet (i.e., earth) runs out of fuel and collapses.",
            ],
            "correct_answers": [
                "A supernova that is the result of two massive stars colliding."
            ],
        },
        {
            "question_id": "q2",
            "prompt": "What process releases the energy that balances the gravitational force of a star and avoids its collapse, as long as enough energy is being produced?",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "Nuclear fission",
                "Chemical combustion",
                "Nuclear fusion",
            ],
            "correct_answers": ["Nuclear fusion"],
        },
        {
            "question_id": "q3",
            "prompt": "Which collision of two objects can lead to the formation of a black hole?",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "Two black holes collide with each other.",
                "Two planets the size of Earth colliding with each other.",
                "A star (e.g., the sun) colliding with a planet (e.g., earth).",
            ],
            "correct_answers": ["Two black holes collide with each other."],
        },
        {
            "question_id": "q4",
            "prompt": "Which of the following chemical elements are an important consideration in the formation process of black holes?",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": ["Hydrogen", "Rubidium", "Barium", "Beryllium"],
            "correct_answers": ["Hydrogen"],
        },
        {
            "question_id": "q5",
            "prompt": "What typically happens when a massive star is near the end of its lifecycle?",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "A black hole forms immediately.",
                "The star dies and becomes a white dwarf.",
                "The star burns heavier elements/fuels, such as helium, carbon or oxygen, leading to a supernova.",
                "The mass of the star forms a planet.",
            ],
            "correct_answers": [
                "The star burns heavier elements/fuels, such as helium, carbon or oxygen, leading to a supernova."
            ],
        },
    ],
}

QUARTO_OBJECTIVE_CHOICE_UNDERSTANDING_POST_QUESTIONNAIRE_PAGE = {
    "type": "form",
    "form_id": "objective_understanding_post_choice",
    "form_title": "Questionnaire 4",
    "allow_revisit": True,
    "subtext": "The following section of the questionnaire will be about your knowledge and ability to assess different game situations.",
    "questions": [
        {
            "question_id": "q1",
            "prompt": "Select the piece that would form a quarto with the three pieces shown.",
            "image_url": "/static/images/quarto_1.jpg",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": ["1", "2", "3"],
            "correct_answers": ["3"],
        },
        {
            "question_id": "q2",
            "prompt": "Select the piece that would form a quarto with the three pieces shown.",
            "image_url": "/static/images/quarto_2.jpg",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "1",
                "2",
                "3",
            ],
            "correct_answers": ["3"],
        },
        {
            "question_id": "q3",
            "prompt": "Choose a piece which you would give to the other person for the next move.",
            "image_url": "/static/images/quarto_3.jpg",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "1",
                "2",
                "3",
            ],
            "correct_answers": ["2"],
        },
        {
            "question_id": "q4",
            "prompt": "The following game situation is given. You are given the marked piece (small, square, light-colored, without a hole) by the other person. Where would you place the piece?",
            "image_url": "/static/images/quarto_4.jpg",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": [
                "A",
                "B",
                "C",
                "D",
            ],
            "correct_answers": ["D"],
        },
        {
            "question_id": "q5",
            "prompt": "The following game situation is given. Which piece would you give to the other person?",
            "image_url": "/static/images/quarto_5.jpg",
            "type": "radio",
            "required": True,
            "attention_check_question": False,
            "options": ["1", "2", "3", "4"],
            "correct_answers": ["1"],
        },
    ],
}

# Sleepcycle page sequence
SLEEPCYCLE_PAGE_SEQUENCE = [
    SLEEPCYCLE_SUBJECTIVE_UNDERSTANDING_PRE_QUESTIONNAIRE_PAGE,
    SLEEPCYCLE_QUESTIONNAIRE_TO_CHAT_TRANSITION_PAGE,
    CHAT_PAGE,
    CHAT_TO_QUESTIONNAIRE_TRANSITION_PAGE,
    SLEEPCYCLE_SUBJECTIVE_UNDERSTANDING_POST_QUESTIONNAIRE_PAGE,
    SLEEPCYCLE_OBJECTIVE_UNDERSTANDING_POST_QUESTIONNAIRE_PAGE,
    EXTERNAL_SOURCES_OPEN_QUESTION_1,
    SLEEPCYCLE_OBJECTIVE_CHOICE_UNDERSTANDING_POST_QUESTIONNAIRE_PAGE,
    EXTERNAL_SOURCES_OPEN_QUESTION_2,
    COCONSTRUCT_POST_QUESTIONNAIRE_PAGE,
]

BLACKHOLES_PAGE_SEQUENCE = [
    BLACKHOLES_SUBJECTIVE_UNDERSTANDING_PRE_QUESTIONNAIRE_PAGE,
    BLACKHOLES_QUESTIONNAIRE_TO_CHAT_TRANSITION_PAGE,
    CHAT_PAGE,
    CHAT_TO_QUESTIONNAIRE_TRANSITION_PAGE,
    BLACKHOLES_SUBJECTIVE_UNDERSTANDING_POST_QUESTIONNAIRE_PAGE,
    BLACKHOLES_OBJECTIVE_UNDERSTANDING_POST_QUESTIONNAIRE_PAGE,
    EXTERNAL_SOURCES_OPEN_QUESTION_1,
    BLACKHOLES_OBJECTIVE_CHOICE_UNDERSTANDING_POST_QUESTIONNAIRE_PAGE,
    EXTERNAL_SOURCES_OPEN_QUESTION_2,
    COCONSTRUCT_POST_QUESTIONNAIRE_PAGE,
]

QUARTO_PAGE_SEQUENCE = [
    QUARTO_SUBJECTIVE_UNDERSTANDING_PRE_QUESTIONNAIRE_PAGE,
    QUARTO_QUESTIONNAIRE_TO_CHAT_TRANSITION_PAGE,
    CHAT_PAGE,
    CHAT_TO_QUESTIONNAIRE_TRANSITION_PAGE,
    QUARTO_SUBJECTIVE_UNDERSTANDING_POST_QUESTIONNAIRE_PAGE,
    QUARTO_OBJECTIVE_UNDERSTANDING_POST_QUESTIONNAIRE_PAGE,
    EXTERNAL_SOURCES_OPEN_QUESTION_1,
    QUARTO_OBJECTIVE_CHOICE_UNDERSTANDING_POST_QUESTIONNAIRE_PAGE,
    EXTERNAL_SOURCES_OPEN_QUESTION_2,
    COCONSTRUCT_POST_QUESTIONNAIRE_PAGE,
]

PAGE_SEQUENCES = {
    "quarto": QUARTO_PAGE_SEQUENCE,
    "sleep": SLEEPCYCLE_PAGE_SEQUENCE,
    "blackholes": BLACKHOLES_PAGE_SEQUENCE,
}
